pub const FFI_COMMAND_BOOTSTRAP: i32 = 0;
pub const FFI_COMMAND_PLAY: i32 = 1;
pub const FFI_COMMAND_PAUSE: i32 = 2;
pub const FFI_COMMAND_SKIP_PREVIOUS: i32 = 3;
pub const FFI_COMMAND_SKIP_NEXT: i32 = 4;
pub const FFI_COMMAND_START_SESSION: i32 = 5;
pub const FFI_COMMAND_END_SESSION: i32 = 6;
pub const FFI_COMMAND_SEARCH: i32 = 7;
pub const FFI_COMMAND_BROWSE: i32 = 8;
pub const FFI_COMMAND_SET_SPEED: i32 = 9;
pub const FFI_COMMAND_SEEK: i32 = 10;
pub const FFI_COMMAND_START_VOICE: i32 = 11;
pub const FFI_COMMAND_STOP_VOICE: i32 = 12;
pub const FFI_COMMAND_PROCESS_VOICE: i32 = 13;
pub const FFI_COMMAND_PLAY_MEDIA_BY_ID: i32 = 14;
pub const FFI_COMMAND_HYDRATE_THEME_PREFERENCE: i32 = 15;
pub const FFI_COMMAND_SET_THEME_PREFERENCE: i32 = 16;
pub const FFI_COMMAND_APPLY_REMOTE_THEME_PREFERENCE: i32 = 17;
pub const FFI_COMMAND_REFRESH_BACKEND_STATUS: i32 = 18;
pub const FFI_COMMAND_LOAD_NEXT_CATALOG_PAGE: i32 = 19;
pub const FFI_COMMAND_UNKNOWN: i32 = -1;

pub const FFI_PLAYBACK_IDLE: i32 = 0;
pub const FFI_PLAYBACK_PLAYING: i32 = 1;
pub const FFI_PLAYBACK_PAUSED: i32 = 2;
pub const FFI_PLAYBACK_BUFFERING: i32 = 3;
pub const FFI_PLAYBACK_ERROR: i32 = 4;

pub const FFI_AUTH_ANONYMOUS: i32 = 0;
pub const FFI_AUTH_AUTHENTICATED: i32 = 1;
pub const FFI_AUTH_LOGIN_REQUIRED: i32 = 2;

pub const FFI_PLATFORM_EVENT_APP_FOREGROUNDED: i32 = 0;
pub const FFI_PLATFORM_EVENT_APP_BACKGROUNDED: i32 = 1;
pub const FFI_PLATFORM_EVENT_SUSPEND_TO_RAM: i32 = 2;
pub const FFI_PLATFORM_EVENT_RESUME_FROM_RAM: i32 = 3;
pub const FFI_PLATFORM_EVENT_UX_RESTRICTIONS_CHANGED: i32 = 4;
pub const FFI_PLATFORM_EVENT_AUDIO_FOCUS_CHANGED: i32 = 5;
pub const FFI_PLATFORM_EVENT_MEDIA_LOADED: i32 = 6;
pub const FFI_PLATFORM_EVENT_MEDIA_ERROR: i32 = 7;
pub const FFI_PLATFORM_EVENT_VEHICLE_DRIVING_STATE_CHANGED: i32 = 8;
pub const FFI_PLATFORM_EVENT_UNKNOWN: i32 = -1;

pub const FFI_RESTRICTION_UNKNOWN: i32 = 0;
pub const FFI_RESTRICTION_UNRESTRICTED: i32 = 1;
pub const FFI_RESTRICTION_RESTRICTED: i32 = 2;

pub const FFI_DRIVING_UNKNOWN: i32 = 0;
pub const FFI_DRIVING_PARKED: i32 = 1;
pub const FFI_DRIVING_IDLING: i32 = 2;
pub const FFI_DRIVING_MOVING: i32 = 3;

pub const FFI_THEME_SYSTEM_DEFAULT: i32 = 0;
pub const FFI_THEME_BAMBOO_GROVE_LIGHT: i32 = 1;
pub const FFI_THEME_MOONLIT_BAMBOO_DARK: i32 = 2;
pub const FFI_THEME_FOREST_TECH_LIGHT: i32 = 3;
pub const FFI_THEME_FOREST_TECH_DARK: i32 = 4;

pub const FFI_PREFERENCE_SOURCE_UNINITIALIZED: i32 = 0;
pub const FFI_PREFERENCE_SOURCE_LOCAL_CACHE: i32 = 1;
pub const FFI_PREFERENCE_SOURCE_LOCAL_USER: i32 = 2;
pub const FFI_PREFERENCE_SOURCE_REMOTE_PROFILE: i32 = 3;

pub const FFI_EVENT_COMMAND_APPLIED: i32 = 0;
pub const FFI_EVENT_LISTENER_REGISTERED: i32 = 1;
pub const FFI_EVENT_ANALYTICS_REPORTED: i32 = 2;

pub const FFI_EFFECT_PLAY: i32 = 0;
pub const FFI_EFFECT_PAUSE: i32 = 1;
pub const FFI_EFFECT_STOP: i32 = 2;
pub const FFI_EFFECT_SEEK: i32 = 3;
pub const FFI_EFFECT_REQUEST_AUDIO_FOCUS: i32 = 4;
pub const FFI_EFFECT_ABANDON_AUDIO_FOCUS: i32 = 5;
pub const FFI_EFFECT_UPDATE_METADATA: i32 = 6;
pub const FFI_EFFECT_SESSION_STARTED: i32 = 7;
pub const FFI_EFFECT_SESSION_ENDED: i32 = 8;
pub const FFI_EFFECT_SET_SPEED: i32 = 9;
pub const FFI_EFFECT_NOTIFY_USER: i32 = 10;
pub const FFI_EFFECT_START_AUDIO_CAPTURE: i32 = 11;
pub const FFI_EFFECT_STOP_AUDIO_CAPTURE: i32 = 12;
pub const FFI_EFFECT_DUCK_AUDIO: i32 = 13;
pub const FFI_EFFECT_UNDUCK_AUDIO: i32 = 14;
pub const FFI_EFFECT_PREPARE_PLAYBACK_SOURCE: i32 = 15;

pub const FFI_ERROR_NONE: i32 = 0;
pub const FFI_ERROR_NOT_FOUND: i32 = 1;
pub const FFI_ERROR_NETWORK: i32 = 2;
pub const FFI_ERROR_PLAYER: i32 = 3;
pub const FFI_ERROR_AUTHENTICATION: i32 = 4;
pub const FFI_ERROR_MEDIA_SKIPPED: i32 = 5;
pub const FFI_ERROR_UNKNOWN: i32 = -1;

pub const FFI_MEDIA_ITEM_TRACK: i32 = 0;
pub const FFI_MEDIA_ITEM_ARTIST: i32 = 1;
pub const FFI_MEDIA_ITEM_ALBUM: i32 = 2;
pub const FFI_MEDIA_ITEM_FOLDER: i32 = 3;
pub const FFI_MEDIA_ITEM_PLAYLIST: i32 = 4;
pub const FFI_MEDIA_ITEM_RADIO_STATION: i32 = 5;
