config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    active: true
    allowedLines: 90
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 8
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 30
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerObject: 20
    allowedFunctionsPerEnum: 20

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
